package com.phukka.macro.devices.mouse;

import com.sun.jna.Pointer;
import com.sun.jna.platform.win32.User32;
import com.sun.jna.platform.win32.WinDef;
import com.sun.jna.platform.win32.WinUser;
import com.phukka.macro.Main;

public class MouseCallback {

    public static int x = 0;
    public static int y = 0;
    public static boolean disableUserMovement = false;

    public WinDef.LRESULT callback(int nCode, WinDef.WPARAM wParam, WinUser.MSLLHOOKSTRUCT lParam) {

        if (nCode >= 0) {
            x = lParam.pt.x;
            y = lParam.pt.y;


            // Use the isUserInput variable to distinguish between user input and programmatic input
            // if the input was generated by the MouseEvent class it will return a 1
            if (wParam.intValue() == 0x0200 && disableUserMovement && lParam.dwExtraInfo.longValue() == 0) {
                return new WinDef.LRESULT(1);
            }

            switch (wParam.intValue()) {
                case 0x0201 -> Main.getScriptContainer().handleKey((short) 2000);
                case 0x0202 -> Main.getScriptContainer().handleKey((short) -2000);
                case 0x0204 -> Main.getScriptContainer().handleKey((short) 2001);
                case 0x0205 -> Main.getScriptContainer().handleKey((short) -2001);
                case 0x0207 -> Main.getScriptContainer().handleKey((short) 2002);
                case 0x0208 -> Main.getScriptContainer().handleKey((short) -2002);

                case 0x020B, 0x020C -> {
                    int whichButton = (wParam.intValue() >> 16) & 0xFFFF;
                    int type = (wParam.intValue() == 0x020B) ? 1 : 2;
                    int button = (whichButton == 0x0001) ? (type == 1 ? 2003 : -2003) : (type == 1 ? 2004 : -2004);
                    Main.getScriptContainer().handleKey((short) button);
                }
            }
        }
        return User32.INSTANCE.CallNextHookEx(null, nCode, wParam, new WinDef.LPARAM(Pointer.nativeValue(lParam.getPointer())));
    }
}