name: Java Run

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '18' # Change to the desired Java version
          distribution: 'adopt' # Change to the appropriate Java distribution

      - name: Build and run
        run: |
          cd src
          javac *.java
          java Main
